### ISSUE TITLE
[TypeError: 0, require(_dependencyMap[13], "(...)-native-image-colors").getColors is not a function (it is undefined)]

### ISSUE THREAD

**Issue by mayankdhiman001** [osamaqarem/react-native-image-colors#95] opened 2024-11-29 08:48 UTC
# Bug

## Environment info

| Library                   | Version |
| ------------------------- | ------- |
| react-native-image-colors | x.x.x   |

## Steps To Reproduce

[TypeError: 0, require(_dependencyMap[13], "(...)-native-image-colors").getColors is not a function (it is undefined)]
1. Install react native image colors
2. install espo requiremnets 
  it works on android but in ios it gives [TypeError: 0, require(_dependencyMap[13], "(...)-native-image-colors").getColors is not a function (it is undefined)]
Describe what you expected to happen:

1. its give colours .. 
2.

**Comment by osamaqarem** [comment] 2024-12-18 03:09
Closing due to incomplete issue description (please provide clearer steps to reproduce).

**Closed by osamaqarem** 2024-12-18 03:09 UTC
Labels: bug
