### ISSUE TITLE
[Android] Fails to build with expo 52 (Inconsistent JVM-target compatibility detected)

### ISSUE THREAD

**Issue by doughsay** [osamaqarem/react-native-image-colors#96] opened 2024-12-01 19:10 UTC
# Bug

re-opening: https://github.com/osamaqarem/react-native-image-colors/issues/94

This package fails to build for android when added to a freshly generated Expo 52 app with nothing else changed.  The error produced is:

```
> Task :react-native-image-colors:compileDebugKotlin FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-image-colors:compileDebugKotlin'.
> Inconsistent JVM-target compatibility detected for tasks 'compileDebugJavaWithJavac' (17) and 'compileDebugKotlin' (21).

  Consider using JVM Toolchain: https://kotl.in/gradle/jvm/toolchain
  Learn more about JVM-target validation: https://kotl.in/gradle/jvm/target-validation

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.
```

## Environment info

| Library                   | Version |
| ------------------------- | ------- |
| react-native-image-colors | 2.4.0   |

I use `asdf` to manage tool versions, here are the exact versions used:

```
bun 1.1.38
java adoptopenjdk-21.0.5+11.0.LTS
nodejs 22.11.0
```

## Steps To Reproduce

1. `bun create expo-app --template`
    * use default template
    * I named it "expo-colors-app"
2. `cd expo-colors-app`
3. `bunx expo install react-native-image-colors`
4. `bunx expo run:android`

Describe what you expected to happen:

I expected the app to compile, but it does not.

## Reproducible sample code

https://github.com/doughsay/expo-colors-app

**Comment by osamaqarem** [comment] 2024-12-18 03:13
Thanks for the sample code. I'm not able to reproduce. 
It looks like you're deviating from the recommended JDK version (adoptopenjdk 21 vs zulu 17):
https://docs.expo.dev/workflow/android-studio-emulator/#install-watchman-and-jdk

I'm pretty sure that's the problem. Please feel free to re-open if it still happens after moving to the recommended JDK version.

**Closed by osamaqarem** 2024-12-18 03:13 UTC
Labels: bug

**Comment by doughsay** [comment] 2024-12-18 21:13
Thanks, I wasn't even aware there was a recommended JDK version.  Thanks for pointing me to it!

**Comment by osamaqarem** [comment] 2024-12-19 07:17
ah i see. expo likely simply recommends what React Native docs do, and that's JDK 17 (also for linux):
https://reactnative.dev/docs/set-up-your-environment?os=linux

at least over there it's also clearly stated:
> You may encounter problems using higher JDK versions.

Updating the expo docs for linux to mention 17 is a fair point 👍
